platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source 'http://gitlab.yuejia100.com.cn/iOS/YJYPods.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'YuGuanJia' do
  pod 'AFNetworking', '~> 3.2.1',:subspecs => ['Reachability', 'Serialization', 'Security', 'NSURLSession']
  pod 'Masonry', '~> 1.1.0'
  pod 'MJRefresh', '~> 3.2.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'SDWebImage', '~> 5.0.3'
  pod 'WMPageController', '~> 2.5.2'
  pod 'YYKit', '~> 1.0.9'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'AMap3DMap-NO-IDFA'
  pod 'AMapSearch-NO-IDFA'
  pod 'AMapLocation-NO-IDFA'
  pod 'XLForm'
  pod 'MJExtension'
  pod 'WebViewJavascriptBridge', '~> 6.0.3',:inhibit_warnings => true
  pod 'QMUIKit', '~> 4.1.3'
  pod 'TZImagePickerController', '~> 3.6.2'
  pod 'Harpy', '~> 4.1.14'
#  pod 'MLeaksFinder', '~> 1.0.0'
  pod 'ChameleonFramework', '~> 2.1.0'
  pod 'YJYTextView'
#  pod 'CocoaLumberjack', '~> 3.7.2'
end


	
